name: scan via gitleaks

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Roda Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_TOKEN: ${{ secrets.GITLEAKS_LICENSE_KEY }}
