name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
      - master  # (opcional, caso use também)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Instalar dependências MkDocs
        run: pip install mkdocs-material pymdown-extensions mkdocs-mermaid2-plugin

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force

